### ISSUE TITLE
Why is language in .travis.yml csharp?

### ISSUE THREAD

**Issue by ps-george** [ymherklotz/FMark#39]
```yml
language: csharp
mono: none
dotnet: 2.1.4
script:
 - cd $TRAVIS_BUILD_DIR/FMark
 - dotnet build -v n
 - dotnet run --no-build

```
